# Generated by Django 5.2.8 on 2025-11-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaResource',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255, verbose_name='Назва/Заголовок')),
                ('description', models.TextField(blank=True, db_column='Description', null=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt', verbose_name='Дата додавання')),
                ('resource_type', models.CharField(choices=[('youtube', 'Відео (YouTube)'), ('tiktok', 'Відео (TikTok)'), ('file', 'Файл (завантаження)')], db_column='ResourceType', max_length=10, verbose_name='Тип ресурсу')),
                ('url', models.URLField(blank=True, db_column='Url', null=True, verbose_name='Посилання (URL)')),
                ('file_data', models.BinaryField(blank=True, db_column='FileData', max_length='max', null=True, verbose_name='Файл (бінарні дані)')),
                ('file_extension', models.CharField(blank=True, db_column='FileExtension', max_length=10, null=True, verbose_name='Розширення файлу')),
            ],
            options={
                'verbose_name': 'Медіа Ресурс',
                'verbose_name_plural': 'Медіа Ресурси',
                'db_table': 'MediaResource',
                'ordering': ['-created_at'],
            },
        ),
    ]
