# Generated by Django 5.2.12 on 2026-04-29 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_media', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100, verbose_name='Назва категорії')),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Категорія медіа',
                'verbose_name_plural': 'Категорії медіа',
                'db_table': 'MediaCategory',
            },
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='category',
            field=models.ForeignKey(blank=True, db_column='CategoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='portal_media.mediacategory', verbose_name='Категорія'),
        ),
    ]
