# Generated by Django 5.2.12 on 2026-04-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_media', '0003_mediacategory_mediaresource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaresource',
            name='external_id',
            field=models.CharField(blank=True, db_column='ExternalID', max_length=255, null=True, unique=True, verbose_name='ID у соцмережі'),
        ),
    ]
