# Generated by Django 5.2.12 on 2026-04-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_media', '0004_mediaresource_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaresource',
            name='resource_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('file', 'Файл')], db_column='ResourceType', max_length=10, verbose_name='Тип ресурсу'),
        ),
    ]
