# Generated by Django 5.2.12 on 2026-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_media', '0005_alter_mediaresource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaresource',
            name='image_url',
            field=models.URLField(blank=True, db_column='ImageUrl', max_length=1000, null=True, verbose_name='URL зображення'),
        ),
    ]
