# Generated by Django 5.2.12 on 2026-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_media', '0006_mediaresource_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaresource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mediaresource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mediaresource',
            name='url',
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='descriptions',
            field=models.JSONField(blank=True, db_column='Descriptions', default=dict, null=True, verbose_name='Описи (UA, EN, IT...)'),
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='titles',
            field=models.JSONField(db_column='Titles', default=dict, verbose_name='Назви (UA, EN, IT...)'),
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='urls',
            field=models.JSONField(blank=True, db_column='Urls', default=dict, null=True, verbose_name='Посилання (URL) для різних мов'),
        ),
    ]
