# Generated by Django 5.2.12 on 2026-08-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal_media", "0007_remove_mediaresource_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("faq", "FAQ Video"),
                    ("tiktok", "TikTok"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("file", "Файл"),
                ],
                db_column="ResourceType",
                max_length=10,
                verbose_name="Тип ресурсу",
            ),
        ),
    ]
