# Generated by Django 5.2.8 on 2025-11-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='TypeName', max_length=64)),
                ('extensions', models.CharField(db_column='Extensions', max_length=255)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'FileTypes',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('base_transaction_id', models.BinaryField(blank=True, db_column='BaseTransactionID', max_length=255, null=True, verbose_name='Базовий ID транзакції')),
                ('message', models.TextField(db_column='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'db_table': 'Message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionFile',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('base_transaction_id', models.BinaryField(blank=True, db_column='BaseTransactionID', max_length=255, null=True, verbose_name='Базовий ID транзакції')),
                ('file_name', models.CharField(db_column='FileName', max_length=255)),
                ('file_extension', models.CharField(db_column='FileExtension', max_length=32)),
                ('file_path', models.TextField(blank=True, db_column='FilePath', null=True)),
                ('file_data', models.BinaryField(blank=True, db_column='FileData', max_length='max', null=True)),
            ],
            options={
                'db_table': 'TransactionFiles',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='TypeName', max_length=64)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TransactionTypes',
            },
        ),
    ]
