# Generated by Django 5.2.8 on 2025-11-10 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='writer',
            field=models.ForeignKey(blank=True, db_column='WriterID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionfile',
            name='file_type',
            field=models.ForeignKey(db_column='FileTypeId', on_delete=django.db.models.deletion.CASCADE, to='records.filetype'),
        ),
        migrations.AddField(
            model_name='transactionfile',
            name='transaction_type',
            field=models.ForeignKey(db_column='TransactionTypeID', on_delete=django.db.models.deletion.CASCADE, related_name='files_by_type', to='records.transactiontype', verbose_name='Тип транзакції'),
        ),
        migrations.AddField(
            model_name='message',
            name='transaction_type',
            field=models.ForeignKey(db_column='TransactionTypeID', on_delete=django.db.models.deletion.CASCADE, related_name='messages_by_type', to='records.transactiontype', verbose_name='Тип транзакції'),
        ),
    ]
