# Generated by Django 5.2.4 on 2025-11-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfile',
            name='thumbnail_data',
            field=models.BinaryField(blank=True, db_column='ThumbnailData', max_length='max', null=True, verbose_name='Зменшена копія даних'),
        ),
    ]
