# Generated by Django 5.2.4 on 2025-12-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_transactionfile_thumbnail_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='writer',
        ),
    ]
