# Generated by Django 5.2.4 on 2025-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_message_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='writer_id',
            field=models.BinaryField(blank=True, db_column='WriterID', max_length=16, null=True, verbose_name='Автор (GUID)'),
        ),
    ]
