# Generated by Django 5.2.4 on 2026-01-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_message_writer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_column='IsRead', default=False, verbose_name='Прочитано'),
        ),
    ]
