# Generated by Django 5.2.4 on 2026-01-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_send',
            field=models.BooleanField(db_column='IsSend', default=False, verbose_name='Сповіщення надіслано'),
        ),
    ]
