# Generated by Django 5.2.4 on 2026-02-24 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_message_is_send'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardConfig',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('layout_name', models.CharField(db_column='LayoutName', default='default', max_length=255)),
                ('config', models.JSONField(db_column='Config', help_text='Масив конфігурації віджетів у форматі JSON')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Налаштування дашборду',
                'verbose_name_plural': 'Налаштування дашбордів',
                'db_table': 'UserDashboard',
            },
        ),
    ]
