# Generated by Django 5.2.4 on 2026-03-02 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_userdashboardconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('STATUS_CHANGED', 'Зміна статусу'), ('NEW_MESSAGE', 'Нове повідомлення'), ('ORDER_CREATED', 'Створено замовлення'), ('ORDER_CANCELLED', 'Скасовано замовлення'), ('PAYMENT_RECEIVED', 'Отримано оплату')], db_column='EventType', max_length=50)),
                ('base_transaction_id', models.BinaryField(blank=True, db_column='BaseTransactionID', max_length=255, null=True, verbose_name='Базовий ID транзакції')),
                ('old_value', models.CharField(blank=True, db_column='OldValue', max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, db_column='NewValue', max_length=255, null=True)),
                ('message', models.TextField(blank=True, db_column='Message', null=True)),
                ('is_read', models.BooleanField(db_column='IsRead', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('transaction_type', models.ForeignKey(db_column='TransactionTypeID', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='records.transactiontype', verbose_name='Тип транзакції')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
                'db_table': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='Notificatio_UserID_a7ec13_idx'), models.Index(fields=['transaction_type', 'base_transaction_id'], name='Notificatio_Transac_f1800b_idx'), models.Index(fields=['event_type'], name='Notificatio_EventTy_98c27e_idx')],
            },
        ),
    ]
