# Generated by Django 5.2.4 on 2026-03-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=255, verbose_name='ID Чату')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Період')),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name="Об'єктОснова")),
                ('text', models.TextField(verbose_name='Текст повідомлення')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_sent_vtg', models.BooleanField(default=False, verbose_name='Відправлено ВТГ')),
                ('operation_type', models.CharField(blank=True, max_length=50, verbose_name='Тип операції')),
                ('is_notification', models.BooleanField(default=False, verbose_name='Це повідомлення')),
                ('event_type', models.CharField(blank=True, max_length=100, verbose_name='Тип події')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ['-timestamp'],
            },
        ),
    ]
