# Generated by Django 5.2.4 on 2026-03-16 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(db_column='AuthorId', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat_id',
            field=models.CharField(db_column='ChatId', db_index=True, max_length=255, verbose_name='ID Чату'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='event_type',
            field=models.CharField(blank=True, db_column='EventType', max_length=100, verbose_name='Тип події'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_notification',
            field=models.BooleanField(db_column='IsNotification', default=False, verbose_name='Це повідомлення'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(db_column='IsRead', default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_sent_vtg',
            field=models.BooleanField(db_column='IsSentVtg', default=False, verbose_name='Відправлено ВТГ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='operation_type',
            field=models.CharField(blank=True, db_column='OperationType', max_length=50, verbose_name='Тип операції'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, db_column='RecipientId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='related_object_id',
            field=models.CharField(blank=True, db_column='RelatedObjectId', max_length=100, null=True, verbose_name="Об'єктОснова"),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(db_column='Text', verbose_name='Текст повідомлення'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_column='Timestamp', verbose_name='Період'),
        ),
    ]
