# Generated by Django 5.2.4 on 2026-03-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_chatmessage_author_alter_chatmessage_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='ChatMessage',
        ),
    ]
