# Generated by Django 5.2.4 on 2026-03-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_chatmessage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='related_object_id',
        ),
    ]
