# Generated by Django 5.2.4 on 2026-03-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_remove_chatmessage_related_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='related_object_id',
            field=models.BinaryField(blank=True, db_column='RelatedObjectId', max_length=255, null=True, verbose_name="Об'єктОснова"),
        ),
    ]
