# Generated by Django 5.2.4 on 2026-03-17 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_chatmessage_related_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='recipient',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='transaction_type',
            field=models.ForeignKey(db_column='TransactionTypeID', default=1, on_delete=django.db.models.deletion.CASCADE, to='records.transactiontype', verbose_name='Тип транзакції'),
            preserve_default=False,
        ),
    ]
