# Generated by Django 5.2.4 on 2026-03-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_remove_chatmessage_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='author',
            field=models.BinaryField(blank=True, db_column='AuthorId', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='recipient',
            field=models.BinaryField(blank=True, db_column='RecipientId', max_length=24, null=True),
        ),
    ]
