# Generated by Django 5.2.4 on 2026-04-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_chatmessage_author_chatmessage_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdashboardconfig',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserDashboardConfig',
        ),
    ]
