# Generated by Codex on 2026-06-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0017_remove_notification_transaction_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatLargeVideoUploadToken",
            fields=[
                ("id", models.BigAutoField(db_column="ID", primary_key=True, serialize=False)),
                ("chat_id", models.CharField(db_column="ChatId", db_index=True, max_length=255)),
                ("token", models.CharField(db_column="Token", db_index=True, max_length=128, unique=True)),
                (
                    "original_file_name",
                    models.CharField(
                        blank=True,
                        db_column="OriginalFileName",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_used", models.BooleanField(db_column="IsUsed", default=False)),
                ("used_at", models.DateTimeField(blank=True, db_column="UsedAt", null=True)),
                ("expires_at", models.DateTimeField(db_column="ExpiresAt")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_column="CreatedAt")),
                (
                    "uploaded_attachment_id",
                    models.BigIntegerField(blank=True, db_column="UploadedAttachmentId", null=True),
                ),
                ("telegram_chat_id", models.BigIntegerField(blank=True, db_column="TelegramChatId", null=True)),
                (
                    "telegram_message_id",
                    models.BigIntegerField(blank=True, db_column="TelegramMessageId", null=True),
                ),
                (
                    "message",
                    models.ForeignKey(
                        db_column="MessageId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="large_video_upload_tokens",
                        to="records.chatmessage",
                    ),
                ),
            ],
            options={
                "db_table": "ChatLargeVideoUploadToken",
            },
        ),
    ]
