# Generated by Django 5.2.12 on 2026-06-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_chatlargevideouploadtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageAttachment',
            fields=[
                ('Id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('AttachmentType', models.CharField(db_column='AttachmentType', max_length=20)),
                ('FileName', models.CharField(blank=True, db_column='FileName', max_length=255, null=True)),
                ('OriginalFileName', models.CharField(blank=True, db_column='OriginalFileName', max_length=255, null=True)),
                ('MimeType', models.CharField(blank=True, db_column='MimeType', max_length=100, null=True)),
                ('FileExtension', models.CharField(blank=True, db_column='FileExtension', max_length=20, null=True)),
                ('FileSize', models.BigIntegerField(blank=True, db_column='FileSize', null=True)),
                ('FileData', models.BinaryField(db_column='FileData', max_length='max')),
                ('DurationSeconds', models.IntegerField(blank=True, db_column='DurationSeconds', null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'ChatMessageAttachment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatTelegramMap',
            fields=[
                ('Id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('ChatId', models.CharField(db_column='ChatId', max_length=255)),
                ('TelegramChatId', models.BigIntegerField(db_column='TelegramChatId')),
                ('TelegramMessageId', models.BigIntegerField(db_column='TelegramMessageId')),
                ('TelegramReplyToMessageId', models.BigIntegerField(blank=True, db_column='TelegramReplyToMessageId', null=True)),
                ('Direction', models.CharField(db_column='Direction', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'ChatTelegramMap',
                'managed': False,
            },
        ),
    ]
