# Generated by Codex on 2026-08-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_chatmessageattachment_chattelegrammap'),
        ('users', '0007_customuser_is_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPortalLink',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('telegram_chat_id', models.BigIntegerField(db_column='TelegramChatId', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('user', models.ForeignKey(
                    db_column='UserID',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='telegram_portal_links',
                    to='users.customuser',
                )),
            ],
            options={'db_table': 'TelegramPortalLink'},
        ),
    ]
