# Generated by Codex on 2026-08-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_telegramportallink'),
        ('users', '0007_customuser_is_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotApiKey',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('key_hash', models.CharField(db_column='KeyHash', max_length=64, unique=True)),
                ('key_prefix', models.CharField(db_column='KeyPrefix', max_length=16)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('last_used_at', models.DateTimeField(blank=True, db_column='LastUsedAt', null=True)),
                ('created_by', models.ForeignKey(
                    blank=True,
                    db_column='CreatedByUserID',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_telegram_bot_keys',
                    to='users.customuser',
                )),
            ],
            options={'db_table': 'TelegramBotApiKeys'},
        ),
    ]
