# Generated by Django 5.2.12 on 2026-08-20 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_calculationidempotencyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAnnouncement',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('body', models.TextField(db_column='Body')),
                ('style', models.CharField(choices=[('info', 'Інформація'), ('success', 'Успіх'), ('warning', 'Попередження'), ('critical', 'Критично'), ('update', 'Оновлення')], db_column='Style', default='info', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('scheduled', 'Заплановано'), ('active', 'Активне'), ('finished', 'Завершено'), ('cancelled', 'Скасовано')], db_column='Status', db_index=True, default='draft', max_length=16)),
                ('audience_mode', models.CharField(choices=[('all', 'Усі'), ('roles', 'Ролі'), ('users', 'Користувачі')], db_column='AudienceMode', default='all', max_length=16)),
                ('audience_roles', models.JSONField(blank=True, db_column='AudienceRoles', default=list)),
                ('scheduled_at', models.DateTimeField(blank=True, db_column='ScheduledAt', db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_column='PublishedAt', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_column='ExpiresAt', db_index=True, null=True)),
                ('require_acknowledgement', models.BooleanField(db_column='RequireAcknowledgement', default=False)),
                ('show_every_login', models.BooleanField(db_column='ShowEveryLogin', default=False)),
                ('action_label', models.CharField(blank=True, db_column='ActionLabel', default='', max_length=80)),
                ('action_url', models.URLField(blank=True, db_column='ActionUrl', default='')),
                ('attachment', models.FileField(blank=True, db_column='Attachment', null=True, upload_to='announcements/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('audience_users', models.ManyToManyField(blank=True, db_table='PortalAnnouncementAudience', related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PortalAnnouncement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalAnnouncementReceipt',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_shown_at', models.DateTimeField(blank=True, db_column='FirstShownAt', null=True)),
                ('last_shown_at', models.DateTimeField(blank=True, db_column='LastShownAt', null=True)),
                ('shown_count', models.PositiveIntegerField(db_column='ShownCount', default=0)),
                ('acknowledged_at', models.DateTimeField(blank=True, db_column='AcknowledgedAt', null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, db_column='DismissedAt', null=True)),
                ('announcement', models.ForeignKey(db_column='AnnouncementID', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='records.portalannouncement')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='announcement_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PortalAnnouncementReceipt',
                'indexes': [models.Index(fields=['user', 'acknowledged_at'], name='PortalAnnou_UserID_ebafa7_idx'), models.Index(fields=['announcement', 'acknowledged_at'], name='PortalAnnou_Announc_a6a1d7_idx')],
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_receipt')],
            },
        ),
    ]
