# Generated by Django 5.2.4 on 2025-09-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_date', models.DateTimeField()),
                ('complaint_order_number', models.TextField(blank=True, null=True)),
                ('complaint_act_number', models.TextField(blank=True, null=True)),
                ('complaint_act_date', models.DateTimeField(blank=True, null=True)),
                ('complaint_description', models.TextField(blank=True, null=True)),
                ('complaint_order_deliver_date', models.DateTimeField()),
                ('complaint_order_define_date', models.DateTimeField()),
                ('complaint_object', models.TextField(blank=True, null=True)),
                ('complaint_complete_date', models.DateTimeField()),
                ('customer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('manager_id', models.CharField(blank=True, max_length=128, null=True)),
                ('complaint_result', models.TextField(blank=True, null=True)),
                ('status_id', models.IntegerField()),
                ('complaint_1c_order', models.TextField(blank=True, null=True)),
                ('complaint_work_start_date', models.DateTimeField()),
                ('complaint_urgent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Complaints',
            },
        ),
        migrations.CreateModel(
            name='ComplaintDecision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_id', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('complaint_issue_id', models.IntegerField()),
                ('complaint_solution_id', models.IntegerField()),
                ('customer_approve', models.BooleanField(default=False)),
                ('manager_approve', models.BooleanField(default=False)),
                ('final_approve_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ComplaintDecisions',
            },
        ),
        migrations.CreateModel(
            name='ComplaintIssue',
            fields=[
                ('complaint_issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_text', models.TextField(blank=True, null=True)),
                ('issue_guid', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ComplaintIssues',
            },
        ),
        migrations.CreateModel(
            name='ComplaintManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_portal_user_id', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'ComplaintManagers',
            },
        ),
        migrations.CreateModel(
            name='ComplaintOrderSeries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serie_guid', models.TextField(blank=True, null=True)),
                ('serie_name', models.TextField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('complaint_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ComplaintOrderSeries',
            },
        ),
        migrations.CreateModel(
            name='ComplaintPhoto',
            fields=[
                ('complaint_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_id', models.IntegerField()),
                ('photo', models.BinaryField(blank=True, max_length='max', null=True)),
                ('photo_name', models.TextField(blank=True, null=True)),
                ('upload_complete', models.BooleanField(default=False)),
                ('photo_ico', models.BinaryField(blank=True, max_length='max', null=True)),
                ('photo_size', models.IntegerField()),
            ],
            options={
                'db_table': 'ComplaintPhotoes',
            },
        ),
        migrations.CreateModel(
            name='ComplaintsMessage',
            fields=[
                ('complaints_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_writer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('message_time', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('complaint_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ComplaintsMessages',
            },
        ),
        migrations.CreateModel(
            name='ComplaintSolution',
            fields=[
                ('complaint_solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_issue_id', models.IntegerField(blank=True, null=True)),
                ('solution_guid', models.TextField(blank=True, null=True)),
                ('solution_text', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ComplaintSolutions',
            },
        ),
    ]
