# Generated by Django 5.2.4 on 2025-09-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_date', models.DateTimeField()),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_deliver_date', models.DateTimeField()),
                ('order_define_date', models.DateTimeField()),
                ('urgent', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField()),
                ('issue', models.BinaryField(max_length=200)),
                ('solution', models.BinaryField(max_length=200)),
            ],
            options={
                'db_table': 'Complaints',
            },
        ),
        migrations.CreateModel(
            name='ComplaintOrderSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_guid', models.CharField(blank=True, max_length=255, null=True)),
                ('serie_name', models.CharField(blank=True, max_length=255, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_series', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.BinaryField(blank=True, max_length='max', null=True)),
                ('photo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_complete', models.BooleanField(default=False)),
                ('photo_ico', models.BinaryField(blank=True, max_length='max', null=True)),
                ('photo_size', models.IntegerField(default=0)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='complaints.complaint')),
            ],
            options={
                'db_table': 'ComplaintPhotos',
            },
        ),
    ]
