# Generated by Django 5.2.4 on 2025-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintorderseries',
            name='serie_guid',
        ),
        migrations.AddField(
            model_name='complaintorderseries',
            name='serie_link',
            field=models.BinaryField(blank=True, max_length=200, null=True),
        ),
    ]
