# Generated by Django 5.2.4 on 2025-09-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaintorderseries_serie_guid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user_id_1C',
            field=models.BinaryField(blank=True, max_length=255, null=True),
        ),
    ]
