# Generated by Django 5.2.4 on 2025-09-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_user_id_1c'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaintorderseries',
            table='ComplaintOrderSeries',
        ),
    ]
