# Generated by Django 5.2.4 on 2025-09-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaintorderseries_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='web_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
