# Generated by Django 5.2.4 on 2025-09-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_remove_complaint_web_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='web_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
