# Generated by Django 5.2.4 on 2025-09-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_web_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='create_date',
        ),
    ]
