# Generated by Django 5.2.4 on 2025-09-23 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_remove_complaint_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintPhoto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='complaint_photos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='complaint_photos/thumbnails/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_photos2', to='complaints.complaint')),
            ],
        ),
    ]
