# Generated by Django 5.2.4 on 2025-09-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaintphoto2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaintphoto2',
            table='ComplaintPhotos2',
        ),
    ]
