# Generated by Django 5.2.4 on 2025-09-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_alter_complaintphoto2_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintphoto2',
            name='thumbnail',
        ),
    ]
