# Generated by Django 5.2.4 on 2025-09-05 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpServiceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(max_length=255, verbose_name='Відділ')),
            ],
            options={
                'db_table': 'HelpServiceContacts',
            },
        ),
        migrations.CreateModel(
            name='HelpServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
                ('call_type', models.IntegerField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.helpservicecontact')),
            ],
            options={
                'db_table': 'HelpServiceLogs',
            },
        ),
    ]
