# Generated by Django 5.2.8 on 2025-11-10 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpServiceContact',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('contact_name', models.CharField(db_column='ContactName', max_length=255)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('telegram_id', models.CharField(blank=True, db_column='TelegramId', max_length=255, null=True)),
                ('department', models.CharField(db_column='Department', max_length=255, verbose_name='Відділ')),
            ],
            options={
                'db_table': 'HelpServiceContact',
            },
        ),
        migrations.CreateModel(
            name='HelpServiceLog',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(db_column='CreateDate')),
                ('success', models.BooleanField(db_column='Success', default=False)),
                ('call_type', models.IntegerField(db_column='CallType')),
                ('contact', models.ForeignKey(db_column='ContactID', on_delete=django.db.models.deletion.CASCADE, to='contact.helpservicecontact')),
            ],
            options={
                'db_table': 'HelpServiceLog',
            },
        ),
    ]
