# Generated by Django 5.2.4 on 2025-09-05 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Посилання на YouTube')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок відео')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_videos', to=settings.AUTH_USER_MODEL, verbose_name='Додав користувач')),
            ],
            options={
                'verbose_name': 'Відео',
                'verbose_name_plural': 'Відео',
                'db_table': 'Video',
                'ordering': ['-created_at'],
            },
        ),
    ]
