# Generated by Django 5.2.4 on 2025-10-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_videocontent_video'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
