# Generated by Django 5.2.4 on 2025-09-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersPortalLogging',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date_time', models.DateTimeField()),
                ('log_ip_address', models.TextField(blank=True, null=True)),
                ('log_action', models.TextField(blank=True, null=True)),
                ('order_portal_user_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'OrdersPortalLoggings',
            },
        ),
    ]
