# Generated by Django 5.2.4 on 2025-09-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Db1SOrderNumber',
            fields=[
                ('db1s_order_number_id', models.AutoField(primary_key=True, serialize=False)),
                ('db1s_order_number', models.TextField(blank=True, null=True)),
                ('db1s_order_status', models.TextField(blank=True, null=True)),
                ('db1s_order_confirm', models.BooleanField(default=False)),
                ('db1s_order_payed', models.BooleanField(default=False)),
                ('db1s_order_date_payed', models.DateTimeField(blank=True, null=True)),
                ('db1s_order_date_create', models.DateTimeField()),
                ('db1s_order_number_constr', models.FloatField()),
                ('order_image', models.BinaryField(blank=True, max_length='max', null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Db1SOrderNumbers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.TextField(blank=True, null=True)),
                ('order_date_create', models.DateTimeField()),
                ('order_date_progress', models.DateTimeField(blank=True, null=True)),
                ('order_date_complete', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('manager_id', models.CharField(blank=True, max_length=128, null=True)),
                ('file', models.TextField(blank=True, null=True)),
                ('status_id', models.IntegerField()),
                ('order_number_contructions', models.FloatField()),
                ('order_portal_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrdersMessage',
            fields=[
                ('orders_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_writer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('message_time', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('order_id', models.IntegerField()),
            ],
            options={
                'db_table': 'OrdersMessages',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_name', models.TextField(blank=True, null=True)),
                ('query_desc', models.TextField(blank=True, null=True)),
                ('query_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Status',
            },
        ),
    ]
