# Generated by Django 5.2.4 on 2025-09-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersUnified',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('Order', 'Order'), ('Complaint', 'Complaint'), ('OrderPart', 'OrderPart')], max_length=20)),
                ('order_number', models.TextField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('progress_date', models.DateTimeField(blank=True, null=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('deliver_date', models.DateTimeField(blank=True, null=True)),
                ('define_date', models.DateTimeField(blank=True, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('object_name', models.TextField(blank=True, null=True)),
                ('file', models.TextField(blank=True, null=True)),
                ('reason_id', models.IntegerField(blank=True, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('act_number', models.TextField(blank=True, null=True)),
                ('act_date', models.DateTimeField(blank=True, null=True)),
                ('complaint_1c_order', models.TextField(blank=True, null=True)),
                ('urgent', models.BooleanField(blank=True, null=True)),
                ('order_number_contructions', models.FloatField(blank=True, null=True)),
                ('order_portal_user_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'OrdersUnified',
            },
        ),
        migrations.DeleteModel(
            name='Db1SOrderNumber',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrdersMessage',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
