# Generated by Django 5.2.4 on 2025-09-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_ordersunified_status_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersunified',
            name='order_portal_user_id',
        ),
    ]
