# Generated by Django 5.2.4 on 2025-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordersunified_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersunified',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
