# Generated by Django 5.2.4 on 2025-09-10 11:30

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_ordersunified_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersunified',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=order.models.order_file_path),
        ),
    ]
