# Generated by Django 5.2.4 on 2025-09-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_ordersunified_updated_at_ordermessage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordermessage',
            table='OrderMessage',
        ),
    ]
