# Generated by Django 5.2.4 on 2025-09-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_ordermessage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersunified',
            name='parent_order',
            field=models.ForeignKey(blank=True, help_text='Вказує на основне замовлення для скарг або дозамовлень', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_records', to='order.ordersunified'),
        ),
    ]
