# Generated by Django 5.2.4 on 2025-09-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_alter_ordermessage_order_delete_ordersunified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number_constructions',
            field=models.FloatField(default=0),
        ),
    ]
