# Generated by Django 5.2.4 on 2025-10-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_message_delete_ordermessage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
