# Generated by Django 5.2.4 on 2025-10-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_message_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
