# Generated by Django 5.2.4 on 2025-09-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Назва файлу')),
                ('file_path', models.CharField(max_length=255, verbose_name='Шлях до файлу')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файли',
                'db_table': 'UploadFiles',
                'ordering': ['-create_date'],
            },
        ),
    ]
