# Generated by Django 5.2.4 on 2025-10-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='file_path',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_base64',
            field=models.TextField(default='', verbose_name='Файл у Base64'),
            preserve_default=False,
        ),
    ]
