# Generated by Django 5.2.4 on 2025-10-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_uploadfile_file_path_uploadfile_file_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_extension',
            field=models.CharField(default='', max_length=10, verbose_name='Розширення файлу'),
            preserve_default=False,
        ),
    ]
