import { useEffect, useMemo, useState } from "react";
import axiosInstance from "../api/axios";
import "./AnnouncementsPage.css";
const roles=["admin","manager","region_manager","dealer"];
const roleLabels={admin:"Адміністратори",manager:"Менеджери",region_manager:"Регіональні менеджери",dealer:"Дилери"};
const templates=[
 {name:"Технічні роботи",icon:"🛠",style:"warning",title:"Планові технічні роботи",body:"У зазначений час портал може бути тимчасово недоступний. Просимо завершити роботу завчасно.",action_label:"Переглянути деталі"},
 {name:"Важливе",icon:"⚠",style:"critical",title:"Важливе повідомлення",body:"Зверніть, будь ласка, увагу на це повідомлення. Воно потребує вашого ознайомлення.",action_label:"Ознайомився",require_acknowledgement:true,show_every_login:true},
 {name:"Нова функція",icon:"✦",style:"update",title:"У порталі з’явилося оновлення",body:"Ми додали нову можливість, щоб ваша робота в порталі була швидшою та зручнішою.",action_label:"Дізнатися більше"},
 {name:"Нагадування",icon:"🔔",style:"info",title:"Нагадування",body:"Будь ласка, перевірте актуальність даних та виконайте необхідну дію в порталі.",action_label:"Відкрити"},
 {name:"Гарні новини",icon:"✓",style:"success",title:"Гарні новини",body:"Роботи завершено. Дякуємо за ваше терпіння та співпрацю!",action_label:"Зрозуміло"},
 {name:"Документ",icon:"📎",style:"info",title:"Новий документ для ознайомлення",body:"Будь ласка, перегляньте прикріплений документ і підтвердьте ознайомлення.",action_label:"Переглянути документ",require_acknowledgement:true,show_every_login:true},
];
const emptyForm={title:"",body:"",style:"info",audience_mode:"all",audience_roles:[],scheduled_at:"",expires_at:"",require_acknowledgement:false,show_every_login:false,action_label:"",action_url:""};
export default function AnnouncementsPage(){
 const [items,setItems]=useState([]),[form,setForm]=useState(emptyForm),[attachment,setAttachment]=useState(null),[receipts,setReceipts]=useState([]),[users,setUsers]=useState([]),[search,setSearch]=useState(""),[selectedUsers,setSelectedUsers]=useState([]),[preview,setPreview]=useState(false);
 const load=()=>axiosInstance.get("/announcements/").then(r=>setItems(r.data)); useEffect(()=>{load();axiosInstance.get("/users/all/").then(r=>setUsers(r.data.users||[]));},[]); const filteredUsers=useMemo(()=>users.filter(u=>(u.full_name||u.username||"").toLowerCase().includes(search.toLowerCase())),[users,search]);
 const save=async e=>{e.preventDefault();const data=new FormData();Object.entries(form).forEach(([k,v])=>data.append(k,Array.isArray(v)?v.join(","):v));data.append("audience_user_ids",selectedUsers.join(","));if(attachment)data.append("attachment",attachment);await axiosInstance.post("/announcements/",data);setForm(emptyForm);setAttachment(null);setSelectedUsers([]);load()};
 const journal=async id=>setReceipts((await axiosInstance.get("/announcements/"+id+"/receipts/")).data); const applyTemplate=template=>{const {name,icon,...values}=template;setForm({...emptyForm,...values});setAttachment(null);setSelectedUsers([])};
 return <main className="announcements-page"><header className="announcements-hero"><div><span>ЦЕНТР КОМУНІКАЦІЙ</span><h1>Розсилки порталу</h1><p>Створюйте вчасні повідомлення, показуйте їх потрібній аудиторії та відстежуйте ознайомлення.</p></div><b>{items.length}<small> створених оголошень</small></b></header><section className="announcement-template-section"><div><span>ШВИДКИЙ СТАРТ</span><h2>Оберіть готовий сценарій</h2></div><div className="announcement-template-grid">{templates.map(template=><button type="button" className={"announcement-template announcement-template--"+template.style} key={template.name} onClick={()=>applyTemplate(template)}><i>{template.icon}</i><b>{template.name}</b></button>)}</div></section><form className="announcements-form" onSubmit={save}><div className="announcements-form-title"><span>СТВОРЕННЯ РОЗСИЛКИ</span><h2>Налаштуйте повідомлення</h2></div>
 <input required placeholder="Заголовок" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required placeholder="Текст повідомлення" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/>
 <div className="announcements-grid"><label>Стиль<select value={form.style} onChange={e=>setForm({...form,style:e.target.value})}><option value="info">Інформація</option><option value="success">Успіх</option><option value="warning">Попередження</option><option value="critical">Критично</option><option value="update">Оновлення</option></select></label><label>Аудиторія<select value={form.audience_mode} onChange={e=>setForm({...form,audience_mode:e.target.value})}><option value="all">Усі користувачі</option><option value="roles">За ролями</option><option value="users">Конкретні користувачі</option></select></label><label>Початок показу<input type="datetime-local" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></label><label>Завершення<input type="datetime-local" value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value})}/></label></div>
 {form.audience_mode==="roles"&&<section className="announcement-role-picker">{roles.map(role=><label key={role}><input type="checkbox" checked={form.audience_roles.includes(role)} onChange={e=>setForm({...form,audience_roles:e.target.checked?[...form.audience_roles,role]:form.audience_roles.filter(item=>item!==role)})}/>{roleLabels[role]}</label>)}</section>}{form.audience_mode==="users"&&<section className="announcement-user-picker"><input placeholder="Пошук користувача" value={search} onChange={e=>setSearch(e.target.value)}/><small>Обрано: {selectedUsers.length}</small><div>{filteredUsers.map(u=><label key={u.id}><input type="checkbox" checked={selectedUsers.includes(u.id)} onChange={e=>setSelectedUsers(e.target.checked?[...selectedUsers,u.id]:selectedUsers.filter(id=>id!==u.id))}/>{u.full_name||u.username} — {u.role}</label>)}</div></section>}<div className="announcements-grid"><input placeholder="Текст кнопки" value={form.action_label} onChange={e=>setForm({...form,action_label:e.target.value})}/><input placeholder="Посилання" value={form.action_url} onChange={e=>setForm({...form,action_url:e.target.value})}/><label>Вкладення<input type="file" accept="image/*,.pdf" onChange={e=>setAttachment(e.target.files[0])}/></label></div>
 <label><input type="checkbox" checked={form.require_acknowledgement} onChange={e=>setForm({...form,require_acknowledgement:e.target.checked})}/> Потрібне підтвердження</label><label><input type="checkbox" checked={form.show_every_login} onChange={e=>setForm({...form,show_every_login:e.target.checked})}/> Показувати до підтвердження</label><div className="announcement-form-actions"><button className="announcement-preview-button" type="button" onClick={()=>setPreview(true)}>◱ Попередній перегляд</button><button className="announcement-send-button">{form.scheduled_at?"Запланувати розсилку":"Опублікувати зараз"}</button></div></form>
 <section className="announcement-history"><div className="announcements-form-title"><span>ЖУРНАЛ</span><h2>Надіслані оголошення</h2></div>{items.map(item=><article className={"announcement-row announcement-row--"+item.style} key={item.id}><div><b>{item.title}</b><p>{item.body}</p><small>{item.status} · отримувачів: {item.stats?.total||0} · підтвердили: {item.stats?.acknowledged||0}</small></div><button onClick={()=>journal(item.id)}>Журнал</button></article>)}</section>
 {preview&&<div className={"portal-announcement portal-announcement--"+form.style}><div className="portal-announcement__card"><div className="portal-announcement__glow"/><div className="portal-announcement__banner"><span className="portal-announcement__icon">{form.style==="critical"||form.style==="warning"?"⚠":form.style==="success"?"✓":form.style==="update"?"✦":"ℹ"}</span><h2>{form.title||"Заголовок повідомлення"}</h2></div><div className="portal-announcement__content"><p>{form.body||"Текст повідомлення"}</p>{attachment&&<div className="portal-announcement__attachment">📎 {attachment.name}</div>}<div className="portal-announcement__actions">{form.action_url&&<button className="portal-announcement__preview-link" type="button">{form.action_label||"Детальніше"}</button>}<button onClick={()=>setPreview(false)}>{form.require_acknowledgement?"✓ Ознайомився":"Зрозуміло"}</button></div></div></div></div>}{receipts.length>0&&<section className="announcements-receipts"><h2>Отримувачі</h2>{receipts.map(row=><p key={row.user_id}>{row.user} ({row.role}) — показів: {row.shown_count}, підтверджено: {row.acknowledged_at?"так":"ні"}</p>)}</section>}</main>
}