# Generated by Django 5.2.4 on 2025-09-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Db1SOrderPartsNumber',
            fields=[
                ('db1s_order_parts_number_id', models.AutoField(primary_key=True, serialize=False)),
                ('db1s_order_parts_number', models.TextField(blank=True, null=True)),
                ('db1s_order_parts_status', models.TextField(blank=True, null=True)),
                ('db1s_order_parts_confirm', models.BooleanField(default=False)),
                ('db1s_order_parts_payed', models.BooleanField(default=False)),
                ('db1s_order_parts_date_payed', models.DateTimeField(blank=True, null=True)),
                ('db1s_order_parts_date_create', models.DateTimeField()),
                ('order_image', models.BinaryField(blank=True, max_length='max', null=True)),
                ('order_parts_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Db1SOrderPartsNumbers',
            },
        ),
        migrations.CreateModel(
            name='OrderParts',
            fields=[
                ('order_parts_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_parts_date', models.DateTimeField()),
                ('order_number', models.TextField(blank=True, null=True)),
                ('order_parts_description', models.TextField(blank=True, null=True)),
                ('order_parts_reason_id', models.IntegerField()),
                ('order_parts_departure_date', models.DateTimeField(blank=True, null=True)),
                ('status_id', models.IntegerField()),
                ('customer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('manager_id', models.CharField(blank=True, max_length=128, null=True)),
                ('order_parts_item_id', models.IntegerField()),
                ('order_parts_delivery_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OrderParts',
            },
        ),
        migrations.CreateModel(
            name='OrderPartsItem',
            fields=[
                ('order_parts_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_parts_item_name', models.TextField(blank=True, null=True)),
                ('order_parts_item_guid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OrderPartsItems',
            },
        ),
        migrations.CreateModel(
            name='OrderPartsReason',
            fields=[
                ('order_parts_reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_parts_reason_name', models.TextField(blank=True, null=True)),
                ('order_parts_reason_guid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OrderPartsReasons',
            },
        ),
    ]
