# Generated by Django 5.2.12 on 2026-07-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusproduct',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Бонусний товар', 'verbose_name_plural': 'Бонусні товари'},
        ),
    ]
