# Generated by Django 5.2.8 on 2025-11-10 14:33

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=50, unique=True, verbose_name='GUID з 1С')),
                ('user_id_1C', models.BinaryField(blank=True, db_column='UserId1C', max_length=255, null=True)),
                ('used', models.BooleanField(db_column='used', default=False)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, db_column='UsedAt', null=True)),
            ],
            options={
                'db_table': 'Invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, db_column='LastLogin', null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(db_column='IsSuperuser', default=False, verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(db_column='IsStaff', default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(db_column='DateJoined', default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_column='Username', max_length=150, unique=True, verbose_name='Логін')),
                ('full_name', models.CharField(blank=True, db_column='FullName', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, db_column='PhoneNumber', max_length=20, null=True)),
                ('expire_date', models.DateTimeField(blank=True, db_column='ExpireDate', null=True)),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('manager', 'Менеджер'), ('operator', 'Оператор'), ('director', 'Директор'), ('region_manager', 'Регіональний менеджер'), ('complaint_manager', 'Менеджер скарг'), ('customer', 'Клієнт')], db_column='Role', default='customer', max_length=30)),
                ('user_id_1C', models.BinaryField(blank=True, db_column='UserId1C', max_length=255, null=True)),
                ('permit_finance_info', models.BooleanField(db_column='PermitFinanceInfo', default=False)),
                ('update_time', models.DateTimeField(auto_now=True, db_column='UpdateTime')),
                ('old_portal_id', models.CharField(blank=True, db_column='OldPortalId', db_index=True, max_length=450, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
