# Generated by Django 5.2.4 on 2025-09-05 06:14

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логін')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото користувача')),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('phone_number_confirmed', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('lockout_end_date', models.DateTimeField(blank=True, null=True)),
                ('lockout_enabled', models.BooleanField(default=False)),
                ('access_failed_count', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('manager', 'Менеджер'), ('operator', 'Оператор'), ('director', 'Директор'), ('region_manager', 'Регіональний менеджер'), ('complaint_manager', 'Менеджер скарг'), ('customer', 'Клієнт')], default='customer', max_length=30)),
                ('order_portal_user_id', models.CharField(blank=True, max_length=255)),
                ('auto_confirm_order', models.BooleanField(default=False)),
                ('permit_finance_info', models.BooleanField(default=False)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
