# Generated by Django 5.2.4 on 2025-09-05 08:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_avatar_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='order_portal_user_id',
            new_name='user_id_1C',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='user',
        ),
        migrations.AddField(
            model_name='invitation',
            name='expire_at',
            field=models.DateTimeField(default=users.models.default_expire_at, verbose_name='Термін дії'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user_id_1C',
            field=models.CharField(default='', max_length=255, verbose_name='ID користувача з 1С'),
            preserve_default=False,
        ),
    ]
