# Generated by Django 5.2.4 on 2025-09-18 06:31

import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='GUID з 1С')),
                ('user_id_1C', models.BinaryField(blank=True, max_length=255, null=True)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(default=users.models.default_expire_at, verbose_name='Термін дії')),
            ],
            options={
                'db_table': 'Invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
