# Generated by Django 5.2.4 on 2025-12-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_externalapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(db_column='EmailConfirmed', default=False, verbose_name='Email підтверджено'),
        ),
    ]
