# Generated by Django 5.2.4 on 2025-09-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_order_portal_user_id_customuser_user_id_1c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='GUID з 1С'),
        ),
    ]
