# Generated by Django 5.2.4 on 2025-09-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_and_regions', '0001_initial'),
        ('users', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations_and_regions.organization'),
        ),
    ]
