# Generated by Django 5.2.4 on 2025-10-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_user_id_1C', models.BinaryField(max_length=255)),
                ('client_user_id_1C', models.BinaryField(max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ManagerClient',
                'unique_together': {('manager_user_id_1C', 'client_user_id_1C')},
            },
        ),
    ]
