# Generated by Django 5.2.4 on 2026-01-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userapikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapikey',
            old_name='user_id',
            new_name='user',
        ),
    ]
