# Generated by Django 5.2.4 on 2025-09-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_invitation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lockout_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lockout_end_date',
        ),
    ]
