# Generated by Django 5.2.4 on 2026-03-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_id_userapikey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, db_column='Email', max_length=254, null=True, verbose_name='email address'),
        ),
    ]
