# Generated by Django 5.2.4 on 2025-10-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_managerclient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagerClient',
            new_name='ManagerDealer',
        ),
        migrations.AlterModelTable(
            name='managerdealer',
            table='ManagerDealer',
        ),
    ]
