# Generated by Django 5.2.12 on 2026-06-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_branch',
            field=models.BooleanField(db_column='IsBranch', default=False),
        ),
    ]
