# Generated by Django 5.2.4 on 2025-10-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_managerclient_managerdealer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerdealer',
            old_name='client_user_id_1C',
            new_name='dealer_user_id_1C',
        ),
        migrations.AlterUniqueTogether(
            name='managerdealer',
            unique_together={('manager_user_id_1C', 'dealer_user_id_1C')},
        ),
    ]
