# Generated by Django 5.2.4 on 2025-10-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_client_user_id_1c_managerdealer_dealer_user_id_1c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='old_user_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
