# Generated by Django 5.2.4 on 2025-10-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_old_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='old_user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
