# Generated by Django 5.2.4 on 2025-10-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_old_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='old_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Старий User ID'),
        ),
    ]
