# Generated by Django 5.2.12 on 2026-09-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_load_all_contractor_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Адміністратор'), ('manager', 'Менеджер'), ('operator', 'Оператор'), ('director', 'Директор'), ('region_manager', 'Регіональний менеджер'), ('branch_manager', 'Керівник філіалу'), ('branches_director', 'Керівник усіх філій'), ('complaint_manager', 'Менеджер скарг'), ('customer', 'Клієнт')], db_column='Role', default='customer', max_length=30),
        ),
    ]
