# Generated by Django 5.2.4 on 2025-09-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPortalUserOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_portal_user_id', models.CharField(max_length=128)),
                ('organization_id', models.IntegerField()),
                ('joined_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'OrderPortalUserOrganizations',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.TextField(blank=True, null=True)),
                ('organization_1c_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Regions',
            },
        ),
    ]
