# Generated by Django 5.2.4 on 2025-09-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_and_regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_1c_link',
            field=models.BinaryField(blank=True, max_length=255, null=True),
        ),
    ]
